### ISSUE TITLE
Editor toolbar position is wrong

### ISSUE THREAD

**Issue by shkbahmad** [michelson/dante2#55]
The toolbar once you select some text is not positioning correctly. It shows up below the selected text.

<img width="766" alt="cms_and_licecap_v1_24__stopped_" src="https://cloud.githubusercontent.com/assets/3406781/24824028/796eda7e-1c1e-11e7-9296-1b9f0936aa18.png">

Any ideas on how this can be fixed? Reproducible here: https://github.com/shkbahmad/Dante2RailsSample

**Comment by michelson** [comment]
Hi , check issue #17

**Comment by shkbahmad** [comment]
@michelson Already did. It's not the same. I'm not using bootstrap anyways.

**Comment by marekolszewski** [comment]
@michelson I'm also having trouble getting the toolbar to appear in the correct position, at least vertically.

**Comment by michelson** [comment]
@shkbahmad, @marekolszewski it's hard to know what is the issue , is possible to see your implementation in order to inspect the implementation ?

**Comment by shkbahmad** [comment]
@michelson I've included a repo in the original post where the issue is reproducible. Doesn't seem to be quite the same as #17 either.

**Comment by Bodacious** [comment]
I'm still seeing errors with Toolbar positioning, but for me it's floating too far above the line.

**Comment by michelson** [comment]
@Bodacious , try changing the `.postArticle` margin-top in order to change the vertical position of toolbar.

**Comment by michelson** [comment]
@shkbahmad do you have a live example to inspect the implementation ?

**Comment by michelson** [comment]
Hi @Bodacious @shkbahmad , the `marginTop` on `.postArticle` strategy had work for you  ?

**Comment by jaspersorrio** [comment]
<img width="490" alt="screen shot 2017-04-27 at 10 09 47 pm" src="https://cloud.githubusercontent.com/assets/10573718/25487791/d7f2ff3e-2b97-11e7-9f84-335500c590ad.png">

Hey guys, we have the same issue here.
What we noticed is that, it's always x distance above the content.

**Comment by Bodacious** [comment]
@michelson nope, changing the margin-top on `.postArticle` has no effect

**Comment by michelson** [comment]
I have to inspect your implementation, otherwise is hard to Tell. Gaving,
could you give me access to your app to test it ?
I recall that this issue was solved in another github issue.

regards

**Comment by Bodacious** [comment]
Yes
  
Will provide access tomorrow   
  
  
  

  
  
>

**Comment by michelson** [comment]
as I said changing the .postContent margin-top did the trick.

![image](https://cloud.githubusercontent.com/assets/11976/25634874/8a6b6bd4-2f52-11e7-8c86-a47c0414ce37.png)

![image](https://cloud.githubusercontent.com/assets/11976/25634889/9affeac4-2f52-11e7-9d8e-8d91f4749286.png)

**Comment by Bodacious** [comment]
I'm still seeing this problem after updating the top margin on `.postArticle`.

**Comment by ayozebarrera** [comment]
Did you solve this guys?

**Comment by jerryc-nguyen** [comment]
@michelson @ayozebarrera @Bodacious Hi, I just update positioning issue. After debug, I see some issue on logic to calculate the top value for tooltip. Using position absolute base on the selection and detect the parent relative coors seem to be too pain. 
My solution is set the position of tooltip to be fixed and update the coors base on selected element on scroll.

https://github.com/jerryc-nguyen/dante2_custom/commit/5cf47fd8cc485b25b20960e6dba2696c0a430a52

p/s: I meet issue when build src from master branch, so I use the code builded to update.

**Comment by michelson** [comment]
hi @jerryc-nguyen , I tought that this was fixed on version 0.4.4. https://github.com/michelson/dante2/releases/tag/v0.4.4, and indeed is working fine in all my implementations.

@jerryc-nguyen , can you add codepen or codesanbox (or similar) to show the issue ? 
thanks!

**Comment by nicolastakashi** [comment]
Hi Guys! Any news about that?

**Comment by AlexDemzz** [comment]
same issue here

**Comment by michelson** [comment]
install Dante2@next
