### ISSUE TITLE
Link creation doesn't work - Caused Dante glitch

### ISSUE THREAD

**Issue by AaronGillBraun** [michelson/dante2#78]
Whenever I try to add a hyperlink to something, it brings up the dialog fine, but as I press enter to set the link, nothing happens. Dante only glitches when I try to hide the dialog by clicking elsewhere on the page. After clicking elsewhere, tooltips are no longer shown, just a grey bar.

![screen shot 2017-12-02 at 8 40 02 pm](https://user-images.githubusercontent.com/15055317/33521568-7f399d18-d7a3-11e7-8ccf-abd24161702e.png)
(pressing enter does nothing)

Then I click elsewhere to hide the popup.
Then:
![screen shot 2017-12-02 at 8 40 28 pm](https://user-images.githubusercontent.com/15055317/33521572-91d80c84-d7a3-11e7-9365-fb577b4832a2.png)
(every subsequent selection shows this)

So I have two questions:
1) How do I fix link creation and get it working?
2) How do I prevent this bug?

**Comment by michelson** [comment]
Hi ! which version of dante are you using ? and which browser ?

I've recorded this directly from demo page: (chrome latest)

![img](http://g.recordit.co/BuKTYxY0Yu.gif)

**Comment by AaronGillBraun** [comment]
I'm using 0.2, as that's the version I could get working. (most other versions give a import error)

**Comment by AaronGillBraun** [comment]
I just downloaded the newest version. I'm trying to implement in React. How would I do this? I can't seem to get past the import phase. Importing Dante from 'Dante2/src/index' returns a failed to compile error. Could you give me a quick example of using the newest version in React. (your tests repo does not work)

**Comment by michelson** [comment]
is hard to tell which is the error without a trace. could you paste it ?

best

**Comment by zcmgyu** [comment]
>  Importing Dante from 'Dante2/src/index' returns a failed to compile error.

I have same your error. I by pass that problem by below steps:
+ Fork latest Dante2 from branch master
+ Change modules.export to ES6 export (By pass error when import DanteEditor)
+ Comment out all #Build stuffs of .gitignore (I don't know why but npm install Dante2 didn't give me build stuff)
+ yarn build your forked Dante2
+ yarn add your Dante2 repo to your project
+ Important thing is remove react and react-dom out of your project's package.json (If you didn't remove it, it would throw below error)

> Element ref was specified as a string (richEditor) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

You can check out my example first commit. It will work for you.
https://github.com/zcmgyu/dante2-demo

**Comment by zcmgyu** [comment]
@michelson By the way, your example also can't paste youtube link and twitter
https://michelson.github.io/dante2/

**Comment by michelson** [comment]
hi @zcmgyu check version 0.4.0 I've fixed the `modules.export` to es6 `export` , I will check the paste behavior now

**Comment by AaronGillBraun** [comment]
After updating to 0.4.0 it works like a charm! Thank you very much.

**Comment by AaronGillBraun** [comment]
I thought I had it working, but the same exact issue is happening with 0.4.0. I must be doing something wrong...
This is my implementation:
```javascript

import React, { Component } from 'react';
import { Dante } from 'Dante2/es/index';

import 'Dante2/dist/DanteStyles.css';

class Editor extends Component {
  componentDidMount() {
     const editor = new Dante({
       el: "editor",
       content: this.props.content
       read_only: !this.props.editable,
       debug: true
     })
     editor.render()
  }

  render(){
    return (
      <div id="editor" className="editor" />
    );
  }
}

export default Editor;

```

**Comment by michelson** [comment]
Does the demo at https://michelson.github.io/Dante2 works for you?

**Comment by michelson** [comment]
I mean, https://michelson.github.io/dante2

**Comment by AaronGillBraun** [comment]
Yes, it does work.
I thought to change the simple implementation to the component based implementation may fix something, but I couldn't because I believe Dante uses react as a dependency, rather than a peer dependency, so that brings up a `You may have two copies of React loaded` issue.

**Comment by michelson** [comment]
Check at dante2-tests repo , it has a customized implementation as a react
component,

Let me know how it goes!

**Comment by AaronGillBraun** [comment]
![screen shot 2017-12-03 at 10 45 12 am](https://user-images.githubusercontent.com/15055317/33526994-13c8a208-d817-11e7-9f61-b3520494aadc.png)
That's the error I get whilst using the demo. This is happening because all the component files imported in the demo use its own copy of react, instead of the one in my projects `node_modules` folder. How do I fix the error?

**Comment by michelson** [comment]
Maybe if we put the react & react Dom as peerDependences in Dante2 will
work right?

**Comment by AaronGillBraun** [comment]
That should work, yes.

**Comment by michelson** [comment]
Aaron, I've pushed a new branch "react-peer" in which I've moved the react
& react DOM to peer deps. To test this you must clone the repo, and run
`yarn build` then clone dante2-tests and change the Dante2 reference in
`package.json` to reference the path where Dante2 was cloned

something like: `"Dante2": "file:/Users/you/work/dante2",` and then `yarn
start` on dante2-tests

tell me how it goes in order to release this as a new version


best

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by AaronGillBraun** [comment]
Installed react-peer branch, tested it out, now getting this error:
![screen shot 2017-12-03 at 12 24 27 pm](https://user-images.githubusercontent.com/15055317/33527806-fcc0d3b0-d824-11e7-96bd-e5fd5e5196d7.png)
Only the peer branch has this error.

**Comment by AaronGillBraun** [comment]
I think this is an issue with webpack not bundling locally installed packages.

**Comment by AaronGillBraun** [comment]
Can confirm, setting `react` and `react-dom` as peer dependencies does fix the `multiple copies of react` issue. I now have gotten Dante2 as a react component working!
You could probably go ahead and merge `react-peer` and `master`. Once you do, I can do some more testing on the npm package.

Although the link issue is still present 😕

**Comment by michelson** [comment]
Hi @AaronGillBraun , which OS & Browser are you using when test the link? are you pressing enter when the focus inside the link input ?

**Comment by AaronGillBraun** [comment]
I am on Mac OSX, using the latest version of chrome. The link thing works on all demos of Dante except my own.

**Comment by michelson** [comment]
can you share your implementation ?

**Comment by AaronGillBraun** [comment]
Sure, I think i'm on to something though. I've been messing around in the source code, and it's clear that the function: 
```javascript
DanteTooltip.prototype.handleInputEnter
```
does not read the enter key. Or more specifically, the onChange event is not reading the enter input.
+ The input is not focussing properly (even though I can type in it)?
+ Something else is wrong.

Right now i'm going to add a function to capture key down instead of on change, as a temporary solution.

My current implementation looks like:
https://gist.github.com/AaronGillBraun/2ae64623b68c5b5c5189e61f753d87db

**Comment by michelson** [comment]
uhmm, it's hard to tell which could be the error, but I guess that you could start again from dante2-test as your example is very similar to it.

**Comment by AaronGillBraun** [comment]
I fixed it!!
Inside `es/components/popovers/toolTip.js` I changed:
```javascript
React.createElement(
        'div',
        { className: 'dante-menu-linkinput' },
        React.createElement('input', {
          className: 'dante-menu-input',
          ref: 'dante_menu_input',
          placeholder: this.props.widget_options.placeholder || 'Paste or type a link',
          onKeyPress: this.handleInputEnter,
          defaultValue: this.getDefaultValue()
        }),
        React.createElement('div', { className: 'dante-menu-button', onMouseDown: this._disableLinkMode })
      ),
```
to
```javascript
React.createElement(
        'div',
        { className: 'dante-menu-linkinput' },
        React.createElement('input', {
          className: 'dante-menu-input',
          ref: 'dante_menu_input',
          placeholder: this.props.widget_options.placeholder || 'Paste or type a link',
          onKeyPress: this.handleInputEnter,
          onKeyDown: this.handleInputEnter,
          defaultValue: this.getDefaultValue()
        }),
        React.createElement('div', { className: 'dante-menu-button', onMouseDown: this._disableLinkMode })
      ),
```

Adding the `handleInputEnter` to a `onKeyDown` event in the `input` element.
This for some reason made it work. Is this worth adding to Dante to prevent other cases of this?

**Comment by AaronGillBraun** [comment]
I still have no clue why this works though. It could be a browser issue (even though it worked elsewhere), but all that matters is it works. 👍

**Comment by michelson** [comment]
you must not edit `es` files, those are generated from build task, if you want to edit the source you must edit files in ./src 
btw glad it worked!

**Comment by AaronGillBraun** [comment]
Ill finish that up. Should I make a PR?

**Comment by michelson** [comment]
please go ahead. 👍
